name: Delete All Older Releases, Tags and Drafts

on:
  workflow_dispatch:

#  schedule:
#    - cron: "0 0 * * *"

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Older Releases and Tags
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 0
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Delete drafts
        uses: hugo19941994/delete-draft-releases@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

