#=================================================
# Description: Build HelmiWrt Packages IPK using GitHub Actions
# Lisence: MIT
# Author: Helmi Amirudin
# Blog: https://helmiau.com
# HelmiWrt by helmiau.com
#=================================================

name: HelmiWrt LuCI App Packages Builder

on:
  workflow_dispatch:
    inputs:
      sdk_image_name:
        description: "OpenWRT SDK image name"
        required: true
        default: "rockchip-armv8-21.02-SNAPSHOT"

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Clone Makefile
        run: |
          git clone --depth=1 https://github.com/helmiau/helmiwrt-packages

      - name: Build IPK ${{ github.event.inputs.sdk_image_name }}
        run: |
          docker run -v "$PWD/build/bin:/home/build/openwrt/bin:Z" \
                     -v "$PWD/build/sdk-build.sh:/home/build/openwrt/luci-app-helmiwrt.sh" \
                     -v "$PWD/luci-app-libernet:/home/build/openwrt/package/luci-app-libernet" \
                     -v "$PWD/luci-app-libernet-bin:/home/build/openwrt/package/luci-app-libernet-bin" \
                     -v "$PWD/luci-app-libernet-plus:/home/build/openwrt/package/luci-app-libernet-plus" \
                     -v "$PWD/luci-app-mikhmon:/home/build/openwrt/package/luci-app-mikhmon" \
                     -v "$PWD/luci-app-openspeedtest:/home/build/openwrt/package/luci-app-openspeedtest" \
                     -v "$PWD/luci-app-shutdown:/home/build/openwrt/package/luci-app-shutdown" \
                     -v "$PWD/luci-app-tinyfm:/home/build/openwrt/package/luci-app-tinyfm" \
                     -v "$PWD/luci-app-v2raya:/home/build/openwrt/package/luci-app-v2raya" \
                     -v "$PWD/luci-app-xderm-bin:/home/build/openwrt/package/luci-app-xderm-bin" \
                     -v "$PWD/luci-app-xderm:/home/build/openwrt/package/luci-app-xderm" \
                     -v "$PWD/luci-app-xderm-limit:/home/build/openwrt/package/luci-app-xderm-limit" \
                     -v "$PWD/luci-app-freevpnsite:/home/build/openwrt/package/luci-app-freevpnsite" \
                     -v "$PWD/luci-app-wegare:/home/build/openwrt/package/luci-app-wegare" \
                    openwrtorg/sdk:${{ github.event.inputs.sdk_image_name }} /bin/bash /home/build/openwrt/luci-app-helmiwrt.sh

      - name: Find Package
        id: find_package
        run: |
          ipk_path=`find build/bin -name 'luci-app-*.ipk'`
          if [[ -z "$ipk_path" ]]; then
            echo "::error title=Find IPK::Couldn't find generated ipk's"
            exit 1
          fi
          echo "::set-output name=ipk_path::$ipk_path"
          echo "::set-output name=ipk_name::$(basename $ipk_path)"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.find_package.outputs.ipk_name }}
          path: ${{ steps.find_package.outputs.ipk_path }}
